/**
 * Maps parsed proto3 schema entities to TypeScript interfaces and enums.
 *
 * Type mapping (matches BifrostQL ProtoSchemaGenerator.GetProtoType output):
 *   - int32 / uint32 / sint32 / fixed32 / sfixed32 → number
 *   - int64 / uint64 / sint64 / fixed64 / sfixed64 → bigint
 *   - float / double                                → number
 *   - string                                        → string
 *   - bool                                          → boolean
 *   - bytes                                         → Uint8Array
 *   - repeated T                                    → T[]
 *   - optional T                                    → T | null
 *
 * Unknown type tokens are passed through verbatim as message/enum references
 * (e.g. `UserRow`, `Status`). Because each message/enum is emitted to its own
 * file, `emitSchema` prepends the cross-file `import` statements those
 * references need — enums are value imports, messages are `import type`.
 */

import type { ProtoEnum, ProtoMessage, ProtoSchema } from "./proto-parser.js";

const FILE_HEADER = "// AUTO-GENERATED by @bifrostql/codegen — do not edit\n";

const SCALAR_MAP: Readonly<Record<string, string>> = {
  int32: "number",
  uint32: "number",
  sint32: "number",
  fixed32: "number",
  sfixed32: "number",
  int64: "bigint",
  uint64: "bigint",
  sint64: "bigint",
  fixed64: "bigint",
  sfixed64: "bigint",
  float: "number",
  double: "number",
  string: "string",
  bool: "boolean",
  bytes: "Uint8Array",
};

/** Returns the TypeScript type expression for a single proto type token. */
export function mapProtoType(protoType: string): string {
  return SCALAR_MAP[protoType] ?? protoType;
}

/** Returns true when the proto type token is a built-in scalar. */
export function isScalar(protoType: string): boolean {
  return Object.prototype.hasOwnProperty.call(SCALAR_MAP, protoType);
}

/**
 * Emits a TypeScript interface for a proto message. Field names are kept
 * verbatim — BifrostQL emits camelCase GraphQL identifiers, so the proto
 * field names are already valid JS property names. Snake_case fields get
 * quoted to remain syntactically valid.
 */
export function emitMessage(msg: ProtoMessage): string {
  const lines: string[] = [];
  lines.push(`export interface ${msg.name} {`);
  for (const field of msg.fields) {
    const baseType = mapProtoType(field.type);
    let fieldType = baseType;
    if (field.repeated) fieldType = `${baseType}[]`;
    if (field.optional && !field.repeated) fieldType = `${baseType} | null`;
    const propName = isValidJsIdent(field.name) ? field.name : JSON.stringify(field.name);
    lines.push(`  ${propName}: ${fieldType};`);
  }
  lines.push("}");
  return lines.join("\n") + "\n";
}

/** Emits a TypeScript const enum mirror of a proto enum. */
export function emitEnum(en: ProtoEnum): string {
  const lines: string[] = [];
  lines.push(`export const enum ${en.name} {`);
  for (const value of en.values) {
    const name = isValidJsIdent(value.name) ? value.name : JSON.stringify(value.name);
    lines.push(`  ${name} = ${value.number},`);
  }
  lines.push("}");
  return lines.join("\n") + "\n";
}

export interface EmittedFile {
  filename: string;
  content: string;
}

/**
 * Builds the cross-file `import` block a message file needs for the
 * message/enum types it references. Enums are emitted as `const enum`s (value
 * imports); messages are interfaces (`import type`). Self-references and scalar
 * types are skipped.
 */
function emitMessageImports(
  msg: ProtoMessage,
  messageNames: ReadonlySet<string>,
  enumNames: ReadonlySet<string>,
): string {
  const typeImports = new Set<string>();
  const valueImports = new Set<string>();
  for (const field of msg.fields) {
    if (isScalar(field.type) || field.type === msg.name) continue;
    if (enumNames.has(field.type)) valueImports.add(field.type);
    else if (messageNames.has(field.type)) typeImports.add(field.type);
  }

  const lines: string[] = [];
  for (const name of [...typeImports].sort()) {
    lines.push(`import type { ${name} } from "./${name}.js";`);
  }
  for (const name of [...valueImports].sort()) {
    lines.push(`import { ${name} } from "./${name}.js";`);
  }
  return lines.length > 0 ? lines.join("\n") + "\n\n" : "";
}

/**
 * Emits a TypeScript file per message + per enum, plus a barrel `index.ts`
 * that re-exports every generated module. Each file gets the AUTO-GENERATED
 * header so consumers know not to hand-edit them.
 */
export function emitSchema(schema: ProtoSchema): EmittedFile[] {
  const files: EmittedFile[] = [];
  const messageNames = new Set(schema.messages.map((m) => m.name));
  const enumNames = new Set(schema.enums.map((e) => e.name));

  for (const msg of schema.messages) {
    const imports = emitMessageImports(msg, messageNames, enumNames);
    files.push({
      filename: `${msg.name}.ts`,
      content: FILE_HEADER + "\n" + imports + emitMessage(msg),
    });
  }

  for (const en of schema.enums) {
    files.push({
      filename: `${en.name}.ts`,
      content: FILE_HEADER + "\n" + emitEnum(en),
    });
  }

  const exportLines = [
    ...schema.messages.map((m) => `export type { ${m.name} } from "./${m.name}.js";`),
    ...schema.enums.map((e) => `export { ${e.name} } from "./${e.name}.js";`),
  ];
  files.push({
    filename: "index.ts",
    content: FILE_HEADER + "\n" + exportLines.join("\n") + (exportLines.length > 0 ? "\n" : ""),
  });

  return files;
}

/**
 * The conventional sub-path, relative to a package `src/` dir, where generated
 * files are emitted when targeting the shared `@bifrostql/types` package. The
 * CLI's `--out packages/@bifrostql/types/src/generated` is the build-time
 * application of this convention; the constant lets tooling and tests refer to
 * it without duplicating the string.
 */
export const SHARED_PACKAGE_GENERATED_DIR = "generated";

/**
 * Returns the barrel re-export line that the `@bifrostql/types` package's own
 * `src/index.ts` uses to surface the generated namespace. Emitter stays pure
 * string generation — the CLI/consumer owns where this line is written.
 */
export function emitSharedBarrelReexport(): string {
  return `export * from "./${SHARED_PACKAGE_GENERATED_DIR}/index.js";`;
}

const JS_IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function isValidJsIdent(name: string): boolean {
  return JS_IDENT.test(name);
}
