packages:
  - docs
  - examples/*
  - packages/*
  - packages/@bifrostql/*
  - samples/HostedSpa/spa
  - src/BifrostQL.UI/frontend
  - tests/BifrostQL.UI.E2E
allowBuilds:
  '@swc/core': true
  esbuild: true
  sharp: true
