using FluentAssertions;
using BifrostQL.Core.QueryModel;
using BifrostQL.Core.QueryModel.TestFixtures;
using Xunit;

namespace BifrostQL.Core.QueryModel;

/// <summary>
/// Tests that SQL generated by GqlObjectQuery uses schema-qualified table references
/// (dialect.TableReference) rather than bare identifier escaping in all code paths.
/// Covers fix/dotnet-review-2026-06-10 FIX 2.
/// </summary>
public sealed class GqlObjectQuerySchemaTests
{
    private static readonly ISqlDialect Dialect = SqlServerDialect.Instance;

    /// <summary>
    /// FIX 2 (line ~217): GetRestrictedSqlParameterized (parent == null path) must use
    /// dialect.TableReference so the FROM clause includes the schema prefix.
    /// </summary>
    [Fact]
    public void AddSqlParameterized_NonDefaultSchemaParentTable_JoinSubqueryUsesSchemaQualifiedFrom()
    {
        // Arrange: Users lives in the "reporting" schema; Orders is in the default (empty) schema.
        var dbModel = DbModelTestFixture.Create()
            .WithTable("Users", t => t
                .WithSchema("reporting")
                .WithPrimaryKey("Id")
                .WithColumn("Name", "nvarchar"))
            .WithTable("Orders", t => t
                .WithPrimaryKey("Id")
                .WithColumn("UserId", "int")
                .WithColumn("Total", "decimal"))
            .WithMultiLink("Users", "Id", "Orders", "UserId", "orders")
            .Build();

        var usersTable = dbModel.GetTableFromDbName("Users");
        var ordersTable = dbModel.GetTableFromDbName("Orders");

        var ordersLink = new GqlObjectQuery
        {
            DbTable = ordersTable,
            GraphQlName = "orders",
            TableName = "Orders",
            SchemaName = "",
            ScalarColumns = { new GqlObjectColumn("Id"), new GqlObjectColumn("Total") }
        };

        var query = new GqlObjectQuery
        {
            DbTable = usersTable,
            TableName = "Users",
            SchemaName = "reporting",
            GraphQlName = "Users",
            Path = "Users",
            ScalarColumns = { new GqlObjectColumn("Id"), new GqlObjectColumn("Name") },
            Links = { ordersLink }
        };

        query.ConnectLinks(dbModel);

        var sqls = new Dictionary<string, ParameterizedSql>();
        var parameters = new SqlParameterCollection();

        // Act
        query.AddSqlParameterized(dbModel, Dialect, sqls, parameters);

        // Assert: main query for Users uses schema-qualified reference (already worked before fix)
        sqls["Users"].Sql.Should().Contain("[reporting].[Users]",
            because: "AddSqlParameterized already used TableReference for the main FROM");

        // Assert: join subquery restricted-select must also use the schema-qualified FROM
        sqls.Should().ContainKey("Users->orders");
        sqls["Users->orders"].Sql.Should().Contain("[reporting].[Users]",
            because: "GetRestrictedSqlParameterized must use TableReference, not bare EscapeIdentifier");
    }

    /// <summary>
    /// FIX 2: when schema is empty/dbo-default, generated SQL must contain just the bare
    /// table name (no leading dot), same as before the fix.
    /// </summary>
    [Fact]
    public void AddSqlParameterized_DefaultSchemaParentTable_JoinSubqueryUsesBareName()
    {
        var dbModel = DbModelTestFixture.Create()
            .WithTable("Users", t => t
                .WithPrimaryKey("Id")
                .WithColumn("Name", "nvarchar"))
            .WithTable("Orders", t => t
                .WithPrimaryKey("Id")
                .WithColumn("UserId", "int")
                .WithColumn("Total", "decimal"))
            .WithMultiLink("Users", "Id", "Orders", "UserId", "orders")
            .Build();

        var usersTable = dbModel.GetTableFromDbName("Users");
        var ordersTable = dbModel.GetTableFromDbName("Orders");

        var ordersLink = new GqlObjectQuery
        {
            DbTable = ordersTable,
            GraphQlName = "orders",
            TableName = "Orders",
            SchemaName = "",
            ScalarColumns = { new GqlObjectColumn("Id"), new GqlObjectColumn("Total") }
        };

        var query = new GqlObjectQuery
        {
            DbTable = usersTable,
            TableName = "Users",
            SchemaName = "",
            GraphQlName = "Users",
            Path = "Users",
            ScalarColumns = { new GqlObjectColumn("Id"), new GqlObjectColumn("Name") },
            Links = { ordersLink }
        };

        query.ConnectLinks(dbModel);

        var sqls = new Dictionary<string, ParameterizedSql>();
        var parameters = new SqlParameterCollection();

        query.AddSqlParameterized(dbModel, Dialect, sqls, parameters);

        sqls["Users->orders"].Sql.Should().Contain("[Users]",
            because: "empty schema produces a bare identifier, same as before the fix");
        sqls["Users->orders"].Sql.Should().NotContain(".[Users]",
            because: "a leading dot would indicate a spurious empty-schema prefix");
    }

    /// <summary>
    /// FIX 2 (line ~261): GetRestrictedSqlParameterized (parent != null path — nested join) must
    /// also use dialect.TableReference for the intermediate table in the recursive query.
    /// </summary>
    [Fact]
    public void AddSqlParameterized_NestedJoins_NonDefaultSchemaIntermediateTable_UsesSchemaQualifiedFrom()
    {
        // Three-level: Companies (default schema) -> Departments (schema "hr") -> Employees (default)
        var dbModel = DbModelTestFixture.Create()
            .WithTable("Companies", t => t
                .WithPrimaryKey("Id")
                .WithColumn("Name", "nvarchar"))
            .WithTable("Departments", t => t
                .WithSchema("hr")
                .WithPrimaryKey("Id")
                .WithColumn("CompanyId", "int")
                .WithColumn("Name", "nvarchar"))
            .WithTable("Employees", t => t
                .WithPrimaryKey("Id")
                .WithColumn("DepartmentId", "int")
                .WithColumn("Name", "nvarchar"))
            .WithMultiLink("Companies", "Id", "Departments", "CompanyId", "departments")
            .WithMultiLink("Departments", "Id", "Employees", "DepartmentId", "employees")
            .Build();

        var companiesTable = dbModel.GetTableFromDbName("Companies");
        var departmentsTable = dbModel.GetTableFromDbName("Departments");
        var employeesTable = dbModel.GetTableFromDbName("Employees");

        var employeesLink = new GqlObjectQuery
        {
            DbTable = employeesTable,
            GraphQlName = "employees",
            TableName = "Employees",
            SchemaName = "",
            ScalarColumns = { new GqlObjectColumn("Id"), new GqlObjectColumn("Name") }
        };

        var departmentsLink = new GqlObjectQuery
        {
            DbTable = departmentsTable,
            GraphQlName = "departments",
            TableName = "Departments",
            SchemaName = "hr",
            ScalarColumns = { new GqlObjectColumn("Id"), new GqlObjectColumn("Name") },
            Links = { employeesLink }
        };

        var query = new GqlObjectQuery
        {
            DbTable = companiesTable,
            TableName = "Companies",
            SchemaName = "",
            GraphQlName = "Companies",
            Path = "Companies",
            ScalarColumns = { new GqlObjectColumn("Id"), new GqlObjectColumn("Name") },
            Links = { departmentsLink }
        };

        query.ConnectLinks(dbModel);

        var sqls = new Dictionary<string, ParameterizedSql>();
        var parameters = new SqlParameterCollection();

        query.AddSqlParameterized(dbModel, Dialect, sqls, parameters);

        // The employees join SQL contains a nested subquery that restricts Departments.
        // The key follows the full ancestor chain: Companies->departments->employees.
        // That nested subquery should reference [hr].[Departments] (the parent != null path).
        sqls.Should().ContainKey("Companies->departments->employees");
        sqls["Companies->departments->employees"].Sql.Should().Contain("[hr].[Departments]",
            because: "the recursive GetRestrictedSqlParameterized (parent != null) must use TableReference");
    }
}
