using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using BifrostQL.Core.Model;
using BifrostQL.Core.Schema;

namespace BifrostQL.Core.QueryModel
{
    public sealed class SchemaLoadTest
    {
        [Fact(Skip = "SqlVisitorToSqlTest.GetFakeTables() emits columns whose GraphQlName isn't declared in the schema text generated by DbSchema.FromModel, so BifrostDispatcher.WireResolvers throws KeyNotFoundException at TypeConfig.FieldFor. Re-enable after aligning the fake-table fixture with the schema generator's contract.")]
        public void FakeSchemaLoadsWithDynamicJoins()
        {
            var model = new DbModel { Tables = SqlVisitorToSqlTest.GetFakeTables(), Metadata = new Dictionary<string, object?>() };
            var schema = DbSchema.FromModel(model);
        }

        [Fact(Skip = "SqlVisitorToSqlTest.GetFakeTables() emits columns whose GraphQlName isn't declared in the schema text generated by DbSchema.FromModel, so BifrostDispatcher.WireResolvers throws KeyNotFoundException at TypeConfig.FieldFor. Re-enable after aligning the fake-table fixture with the schema generator's contract.")]
        public void FakeSchemaLoadsWithoutDynamicJoins()
        {
            var model = new DbModel { Tables = SqlVisitorToSqlTest.GetFakeTables(), Metadata = new Dictionary<string, object?>() { { "dynamic-joins", "false" } } };
            var schema = DbSchema.FromModel(model);
        }
    }
}
