using FluentAssertions;
using Microsoft.SqlServer.TransactSql.ScriptDom;
using Xunit;

namespace BifrostQL.Core.QueryModel;

/// <summary>
/// Validates that SQL generated by the dialect and builders produces syntactically valid T-SQL
/// using Microsoft's official SQL Server parser (ScriptDom).
/// </summary>
public sealed class SqlSyntaxValidationTest
{
    private readonly TSql160Parser _parser = new(initialQuotedIdentifiers: true);
    private readonly SqlServerDialect _dialect = SqlServerDialect.Instance;

    #region Helper Methods

    private (bool IsValid, IList<ParseError> Errors) ValidateSql(string sql)
    {
        using var reader = new StringReader(sql);
        _parser.Parse(reader, out var errors);
        return (errors.Count == 0, errors);
    }

    private void AssertValidSql(string sql)
    {
        var (isValid, errors) = ValidateSql(sql);
        isValid.Should().BeTrue(
            $"SQL should be valid but got {errors.Count} error(s): {string.Join("; ", errors.Select(e => $"Line {e.Line}: {e.Message}"))}.\nSQL: {sql}");
    }

    #endregion

    #region SqlServerDialect.EscapeIdentifier Validation

    [Theory]
    [InlineData("Users")]
    [InlineData("my_table")]
    [InlineData("Table With Spaces")]
    [InlineData("SELECT")]  // Reserved word
    [InlineData("123numeric")]
    [InlineData("special-chars_123")]
    public void EscapeIdentifier_ProducesValidSqlIdentifier(string identifier)
    {
        // Arrange
        var escaped = _dialect.EscapeIdentifier(identifier);

        // Act
        var sql = $"SELECT * FROM {escaped}";

        // Assert
        AssertValidSql(sql);
    }

    #endregion

    #region SqlServerDialect.TableReference Validation

    [Theory]
    [InlineData(null, "Users")]
    [InlineData("", "Users")]
    [InlineData("dbo", "Users")]
    [InlineData("sales", "Orders")]
    [InlineData("HumanResources", "Employee")]
    public void TableReference_ProducesValidSqlTableRef(string? schema, string table)
    {
        // Arrange
        var tableRef = _dialect.TableReference(schema, table);

        // Act
        var sql = $"SELECT * FROM {tableRef}";

        // Assert
        AssertValidSql(sql);
    }

    [Fact]
    public void TableReference_InJoinQuery_ProducesValidSql()
    {
        // Arrange
        var users = _dialect.TableReference("dbo", "Users");
        var orders = _dialect.TableReference("sales", "Orders");

        // Act
        var sql = $"SELECT u.Id, o.OrderDate FROM {users} u INNER JOIN {orders} o ON u.Id = o.UserId";

        // Assert
        AssertValidSql(sql);
    }

    #endregion

    #region SqlServerDialect.Pagination Validation

    [Theory]
    [InlineData(null, null, null)]
    [InlineData(null, 0, 10)]
    [InlineData(null, 50, 25)]
    [InlineData(null, 100, -1)]  // Unlimited
    public void Pagination_WithNullSortColumns_ProducesValidSql(
        IEnumerable<string>? sortColumns, int? offset, int? limit)
    {
        // Arrange
        var pagination = _dialect.Pagination(sortColumns, offset, limit);

        // Act
        var sql = $"SELECT * FROM [Users]{pagination}";

        // Assert
        AssertValidSql(sql);
    }

    [Fact]
    public void Pagination_WithSingleSortColumn_ProducesValidSql()
    {
        // Arrange
        var sortColumns = new[] { "[Name] ASC" };
        var pagination = _dialect.Pagination(sortColumns, 0, 10);

        // Act
        var sql = $"SELECT * FROM [Users]{pagination}";

        // Assert
        AssertValidSql(sql);
    }

    [Fact]
    public void Pagination_WithMultipleSortColumns_ProducesValidSql()
    {
        // Arrange
        var sortColumns = new[] { "[LastName] ASC", "[FirstName] DESC", "[Id] ASC" };
        var pagination = _dialect.Pagination(sortColumns, 20, 50);

        // Act
        var sql = $"SELECT * FROM [Users]{pagination}";

        // Assert
        AssertValidSql(sql);
    }

    [Theory]
    [InlineData(0, 10)]
    [InlineData(0, 100)]
    [InlineData(1000, 50)]
    [InlineData(0, 1000000)]
    public void Pagination_VariousOffsetAndLimit_ProducesValidSql(int offset, int limit)
    {
        // Arrange
        var pagination = _dialect.Pagination(new[] { "[Id]" }, offset, limit);

        // Act
        var sql = $"SELECT Id, Name FROM [dbo].[Users]{pagination}";

        // Assert
        AssertValidSql(sql);
    }

    #endregion

    #region SqlServerDialect.LikePattern Validation

    [Theory]
    [InlineData(LikePatternType.Contains)]
    [InlineData(LikePatternType.StartsWith)]
    [InlineData(LikePatternType.EndsWith)]
    public void LikePattern_AllPatternTypes_ProduceValidSql(LikePatternType patternType)
    {
        // Arrange
        var pattern = _dialect.LikePattern("@searchTerm", patternType);
        var op = _dialect.GetOperator("_contains");

        // Act
        var sql = $"SELECT * FROM [Users] WHERE [Name] {op} {pattern}";

        // Assert
        AssertValidSql(sql);
    }

    [Fact]
    public void LikePattern_InComplexWhereClause_ProducesValidSql()
    {
        // Arrange
        var containsPattern = _dialect.LikePattern("@name", LikePatternType.Contains);
        var startsWithPattern = _dialect.LikePattern("@email", LikePatternType.StartsWith);

        // Act
        var sql = $@"SELECT * FROM [Users]
                     WHERE [Name] LIKE {containsPattern}
                     AND [Email] LIKE {startsWithPattern}
                     AND [Active] = 1";

        // Assert
        AssertValidSql(sql);
    }

    #endregion

    #region SqlServerDialect.GetOperator Validation

    [Theory]
    [InlineData("_eq", "[Status]", "@p0")]
    [InlineData("_neq", "[Type]", "@p0")]
    [InlineData("_lt", "[Age]", "@p0")]
    [InlineData("_lte", "[Price]", "@p0")]
    [InlineData("_gt", "[Quantity]", "@p0")]
    [InlineData("_gte", "[Rating]", "@p0")]
    public void GetOperator_ComparisonOperators_ProduceValidSql(string op, string column, string param)
    {
        // Arrange
        var sqlOp = _dialect.GetOperator(op);

        // Act
        var sql = $"SELECT * FROM [Products] WHERE {column} {sqlOp} {param}";

        // Assert
        AssertValidSql(sql);
    }

    [Theory]
    [InlineData("_in")]
    [InlineData("_nin")]
    public void GetOperator_InOperators_ProduceValidSql(string op)
    {
        // Arrange
        var sqlOp = _dialect.GetOperator(op);

        // Act
        var sql = $"SELECT * FROM [Users] WHERE [Status] {sqlOp} (@p0, @p1, @p2)";

        // Assert
        AssertValidSql(sql);
    }

    [Theory]
    [InlineData("_between")]
    [InlineData("_nbetween")]
    public void GetOperator_BetweenOperators_ProduceValidSql(string op)
    {
        // Arrange
        var sqlOp = _dialect.GetOperator(op);

        // Act
        var sql = $"SELECT * FROM [Orders] WHERE [OrderDate] {sqlOp} @startDate AND @endDate";

        // Assert
        AssertValidSql(sql);
    }

    #endregion

    #region ParameterizedSql Integration Validation

    [Fact]
    public void ParameterizedSql_BuildingSelectQuery_ProducesValidSql()
    {
        // Arrange
        var collection = new SqlParameterCollection();
        var userId = collection.AddParameter(42, "int");

        var table = _dialect.EscapeIdentifier("Users");
        var select = new ParameterizedSql($"SELECT * FROM {table}", collection.Parameters);
        var where = new ParameterizedSql($" WHERE [Id] = {userId}", Array.Empty<SqlParameterInfo>());

        // Act
        var result = select.Append(where);

        // Assert
        AssertValidSql(result.Sql);
    }

    [Fact]
    public void ParameterizedSql_BuildingComplexQuery_ProducesValidSql()
    {
        // Arrange
        var collection = new SqlParameterCollection();
        var name = collection.AddParameter("John%", "nvarchar");
        var minAge = collection.AddParameter(18, "int");
        var maxAge = collection.AddParameter(65, "int");

        var table = _dialect.TableReference("dbo", "Users");
        var likePattern = _dialect.LikePattern(name, LikePatternType.StartsWith);
        var pagination = _dialect.Pagination(new[] { "[LastName] ASC", "[FirstName] ASC" }, 0, 50);

        // Act
        var sql = $"SELECT [Id], [FirstName], [LastName], [Age] FROM {table} " +
                  $"WHERE [FirstName] LIKE {likePattern} " +
                  $"AND [Age] BETWEEN {minAge} AND {maxAge}" +
                  pagination;

        // Assert
        AssertValidSql(sql);
    }

    [Fact]
    public void ParameterizedSql_BuildingInsertQuery_ProducesValidSql()
    {
        // Arrange
        var collection = new SqlParameterCollection();
        var firstName = collection.AddParameter("John", "nvarchar");
        var lastName = collection.AddParameter("Doe", "nvarchar");
        var email = collection.AddParameter("john@example.com", "nvarchar");

        var table = _dialect.TableReference("dbo", "Users");
        var identity = _dialect.LastInsertedIdentity;

        // Act
        var sql = $"INSERT INTO {table} ([FirstName], [LastName], [Email]) " +
                  $"VALUES ({firstName}, {lastName}, {email}); " +
                  $"SELECT {identity};";

        // Assert
        AssertValidSql(sql);
    }

    [Fact]
    public void ParameterizedSql_BuildingUpdateQuery_ProducesValidSql()
    {
        // Arrange
        var collection = new SqlParameterCollection();
        var newStatus = collection.AddParameter("Active", "nvarchar");
        var updatedAt = collection.AddParameter(DateTime.UtcNow, "datetime2");
        var userId = collection.AddParameter(42, "int");

        var table = _dialect.TableReference("dbo", "Users");

        // Act
        var sql = $"UPDATE {table} SET [Status] = {newStatus}, [UpdatedAt] = {updatedAt} WHERE [Id] = {userId}";

        // Assert
        AssertValidSql(sql);
    }

    [Fact]
    public void ParameterizedSql_BuildingDeleteQuery_ProducesValidSql()
    {
        // Arrange
        var collection = new SqlParameterCollection();
        var userId = collection.AddParameter(42, "int");

        var table = _dialect.TableReference("dbo", "Users");

        // Act
        var sql = $"DELETE FROM {table} WHERE [Id] = {userId}";

        // Assert
        AssertValidSql(sql);
    }

    #endregion

    #region SqlParameterCollection IN Clause Validation

    [Fact]
    public void SqlParameterCollection_InClause_ProducesValidSql()
    {
        // Arrange
        var collection = new SqlParameterCollection();
        var ids = new object?[] { 1, 2, 3, 4, 5 };
        var paramNames = collection.AddParameters(ids, "int");

        // Act
        var sql = $"SELECT * FROM [Users] WHERE [Id] IN ({paramNames})";

        // Assert
        AssertValidSql(sql);
    }

    [Fact]
    public void SqlParameterCollection_LargeInClause_ProducesValidSql()
    {
        // Arrange
        var collection = new SqlParameterCollection();
        var ids = Enumerable.Range(1, 100).Cast<object?>().ToArray();
        var paramNames = collection.AddParameters(ids, "int");

        // Act
        var sql = $"SELECT * FROM [Users] WHERE [Id] IN ({paramNames})";

        // Assert
        AssertValidSql(sql);
    }

    #endregion

    #region Complex Query Scenarios

    [Fact]
    public void ComplexJoinQuery_WithAllDialectFeatures_ProducesValidSql()
    {
        // Arrange
        var collection = new SqlParameterCollection();
        var minOrderTotal = collection.AddParameter(100.00m, "decimal");
        var status = collection.AddParameter("Completed", "nvarchar");
        var searchTerm = collection.AddParameter("Premium", "nvarchar");

        var users = _dialect.TableReference("dbo", "Users");
        var orders = _dialect.TableReference("sales", "Orders");
        var products = _dialect.TableReference("inventory", "Products");
        var containsPattern = _dialect.LikePattern(searchTerm, LikePatternType.Contains);
        var pagination = _dialect.Pagination(new[] { "o.[OrderDate] DESC", "u.[LastName] ASC" }, 0, 25);

        // Act
        var sql = $@"SELECT u.[Id], u.[FirstName], u.[LastName], o.[OrderId], o.[Total], p.[ProductName]
                     FROM {users} u
                     INNER JOIN {orders} o ON u.[Id] = o.[UserId]
                     INNER JOIN {products} p ON o.[ProductId] = p.[Id]
                     WHERE o.[Total] >= {minOrderTotal}
                     AND o.[Status] = {status}
                     AND p.[Name] LIKE {containsPattern}
                     {pagination}";

        // Assert
        AssertValidSql(sql);
    }

    [Fact]
    public void SubqueryWithParameterizedConditions_ProducesValidSql()
    {
        // Arrange
        var collection = new SqlParameterCollection();
        var threshold = collection.AddParameter(1000, "int");
        var category = collection.AddParameter("Electronics", "nvarchar");

        var orders = _dialect.TableReference("dbo", "Orders");
        var products = _dialect.TableReference("dbo", "Products");

        // Act
        var sql = $@"SELECT * FROM {orders} o
                     WHERE o.[ProductId] IN (
                         SELECT p.[Id] FROM {products} p
                         WHERE p.[Category] = {category}
                         AND p.[Price] > {threshold}
                     )";

        // Assert
        AssertValidSql(sql);
    }

    [Fact]
    public void AggregateQueryWithGroupBy_ProducesValidSql()
    {
        // Arrange
        var collection = new SqlParameterCollection();
        var minCount = collection.AddParameter(5, "int");

        var orders = _dialect.TableReference("sales", "Orders");
        var pagination = _dialect.Pagination(new[] { "TotalOrders DESC" }, 0, 10);

        // Act
        var sql = $@"SELECT [CustomerId], COUNT(*) AS TotalOrders, SUM([Amount]) AS TotalAmount
                     FROM {orders}
                     GROUP BY [CustomerId]
                     HAVING COUNT(*) >= {minCount}
                     {pagination}";

        // Assert
        AssertValidSql(sql);
    }

    #endregion

    #region Edge Cases and Potential SQL Injection Patterns

    [Fact]
    public void EscapeIdentifier_WithSqlInjectionAttempt_StillProducesValidSql()
    {
        // Arrange - attempting SQL injection through identifier
        var maliciousIdentifier = "Users]; DROP TABLE Users; --";
        var escaped = _dialect.EscapeIdentifier(maliciousIdentifier);

        // Act
        var sql = $"SELECT * FROM {escaped}";

        // Assert - The SQL is valid (though the table name is weird)
        AssertValidSql(sql);
    }

    [Fact]
    public void ParameterizedSql_ChainedOperations_ProducesValidSql()
    {
        // Arrange
        var select = new ParameterizedSql("SELECT * FROM [Users]", Array.Empty<SqlParameterInfo>());
        var where = new ParameterizedSql(" WHERE [Active] = 1", Array.Empty<SqlParameterInfo>());
        var and = new ParameterizedSql(" AND [Role] = @p0", new[] { new SqlParameterInfo("@p0", "Admin", "nvarchar") });
        var orderBy = new ParameterizedSql(" ORDER BY [CreatedAt] DESC", Array.Empty<SqlParameterInfo>());
        var offset = new ParameterizedSql(" OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY", Array.Empty<SqlParameterInfo>());

        // Act
        var result = select.Append(where).Append(and).Append(orderBy).Append(offset);

        // Assert
        AssertValidSql(result.Sql);
        result.Parameters.Should().HaveCount(1);
    }

    #endregion
}
