/**
 * @module types/schema
 * 
 * TypeScript type definitions for database schema metadata.
 * These types represent the structure returned by the _dbSchema GraphQL query.
 */

/**
 * Metadata attached to tables for custom behavior configuration.
 * @interface TableMetadata
 */
export interface TableMetadata {
  /** Lookup configuration for reference tables */
  type?: {
    type: 'lookup';
    id: string;
    label: string;
  };
  [key: string]: any;
}

/**
 * Lookup table metadata defining ID and label columns.
 * @interface LookupMetadata
 */
export interface LookupMetadata {
  type: 'lookup';
  id: string;
  label: string;
}

/**
 * Column-level metadata for custom configuration.
 * @interface ColumnMetadata
 */
export interface ColumnMetadata {
  [key: string]: string | LookupMetadata | undefined;
}

/**
 * Column definition from database schema introspection.
 * @interface Column
 */
export interface Column {
  /** Original database column name */
  dbName: string;
  /** GraphQL field name for the column */
  graphQlName: string;
  /** Alias for graphQlName */
  name: string;
  /** Human-readable label for the column */
  label: string;
  /** GraphQL parameter type (e.g., "String", "Int!") */
  paramType: string;
  /** Database-specific type (e.g., "nvarchar", "int") */
  dbType: string;
  /** Whether this column is part of the primary key */
  isPrimaryKey: boolean;
  /** Whether this column is auto-generated by the database */
  isIdentity: boolean;
  /** Whether this column allows NULL values */
  isNullable: boolean;
  /** Whether this column is read-only (e.g., computed columns) */
  isReadOnly: boolean;
  /** Custom metadata for the column */
  metadata: ColumnMetadata;
  /** Maximum string length (for validation) */
  maxLength?: number;
  /** Minimum string length (for validation) */
  minLength?: number;
  /** Minimum numeric value (for validation) */
  min?: number;
  /** Maximum numeric value (for validation) */
  max?: number;
  /** Step increment for numeric inputs */
  step?: number;
  /** Regex pattern for validation */
  pattern?: string;
  /** Error message for pattern validation failures */
  patternMessage?: string;
  /** HTML input type override */
  inputType?: 'text' | 'email' | 'url' | 'tel' | 'date' | 'datetime-local' | 'number' | 'password' | 'search';
  /** Default value for new records */
  defaultValue?: string;
  /** Allowed enum values */
  enumValues?: string[];
  /** Display labels for enum values */
  enumLabels?: string[];
}

/**
 * Relationship join definition between tables.
 * @interface Join
 */
export interface Join {
  /** Name of the join relationship */
  name: string;
  /** Column names in the source table */
  sourceColumnNames: string[];
  /** Target table name */
  destinationTable: string;
  /** Column names in the target table */
  destinationColumnNames: string[];
}

/**
 * Table definition from database schema introspection.
 * @interface Table
 */
export interface Table {
  /** Original database table name */
  dbName: string;
  /** GraphQL type name for the table */
  graphQlName: string;
  /** Alias for graphQlName */
  name: string;
  /** Human-readable label for the table */
  label: string;
  /** Column used as the display label for foreign key references */
  labelColumn: string;
  /** Primary key column names */
  primaryKeys: string[];
  /** Whether this table supports mutations */
  isEditable: boolean;
  /** Custom metadata for the table */
  metadata: TableMetadata;
  /** Column definitions */
  columns: Column[];
  /** One-to-many relationship joins */
  multiJoins: Join[];
  /** Many-to-one relationship joins */
  singleJoins: Join[];
}

/**
 * Schema context value containing database metadata and loading state.
 * @interface Schema
 */
export interface Schema {
  /** Whether schema data is currently loading */
  loading: boolean;
  /** Error object if schema loading failed, null otherwise */
  error: { message: string} | null;
  /** Array of table definitions */
  data: Table[];
  /** Find a table by its GraphQL name */
  findTable: (tableName: string) => Table | undefined;
}
