/**
 * @module types/schema
 * 
 * TypeScript type definitions for database schema metadata.
 * These types represent the structure returned by the _dbSchema GraphQL query.
 */

/**
 * Metadata attached to tables for custom behavior configuration.
 * @interface TableMetadata
 */
export interface TableMetadata {
  /** Lookup configuration for reference tables */
  type?: LookupMetadata;
  /** Other free-form metadata entries keyed by metadata name (parsed from key/value pairs). */
  [key: string]: string | LookupMetadata | undefined;
}

/**
 * Lookup table metadata defining ID and label columns.
 * @interface LookupMetadata
 */
export interface LookupMetadata {
  type: 'lookup';
  id: string;
  label: string;
}

/**
 * Column-level metadata for custom configuration.
 * @interface ColumnMetadata
 */
export interface ColumnMetadata {
  [key: string]: string | LookupMetadata | undefined;
}

/**
 * Column definition from database schema introspection.
 * @interface Column
 */
export interface Column {
  /** Original database column name */
  dbName: string;
  /** GraphQL field name for the column */
  graphQlName: string;
  /** Alias for graphQlName */
  name: string;
  /** Human-readable label for the column */
  label: string;
  /** GraphQL parameter type (e.g., "String", "Int!") */
  paramType: string;
  /** Database-specific type (e.g., "nvarchar", "int") */
  dbType: string;
  /** Whether this column is part of the primary key */
  isPrimaryKey: boolean;
  /** Whether this column is auto-generated by the database */
  isIdentity: boolean;
  /** Whether this column allows NULL values */
  isNullable: boolean;
  /** Whether this column is read-only (e.g., computed columns) */
  isReadOnly: boolean;
  /** Custom metadata for the column */
  metadata: ColumnMetadata;
  /** Maximum string length (for validation) */
  maxLength?: number;
  /** Minimum string length (for validation) */
  minLength?: number;
  /** Minimum numeric value (for validation) */
  min?: number;
  /** Maximum numeric value (for validation) */
  max?: number;
  /** Step increment for numeric inputs */
  step?: number;
  /** Regex pattern for validation */
  pattern?: string;
  /** Error message for pattern validation failures */
  patternMessage?: string;
  /** HTML input type override */
  inputType?: 'text' | 'email' | 'url' | 'tel' | 'date' | 'datetime-local' | 'number' | 'password' | 'search';
  /** Default value for new records */
  defaultValue?: string;
  /** Allowed enum values */
  enumValues?: string[];
  /** Display labels for enum values */
  enumLabels?: string[];
}

/**
 * Relationship join definition between tables.
 * @interface Join
 */
export interface Join {
  /** Descriptive relationship name retained for compatibility; do not use it as the query field. */
  name: string;
  /** GraphQL selection field for this relationship on the source table. May differ from destinationTable for aliases such as self-FK child collections. */
  fieldName?: string;
  /** Column names in the source table */
  sourceColumnNames: string[];
  /** Target table/type name. Use for schema lookup and navigation, not as the relationship selection field when fieldName is present. */
  destinationTable: string;
  /** Column names in the target table */
  destinationColumnNames: string[];
  /** True for a polymorphic child link — the relation carries a server-side
   *  discriminator predicate (entity_type) rather than a plain FK. Such drills
   *  must keep the MODEL B parent traversal so the server injects the
   *  discriminator; a flat FK filter would leak sibling-type rows. */
  isPolymorphic?: boolean;
  /** Discriminator column backing a polymorphic link (when isPolymorphic). */
  polymorphicTypeColumn?: string;
  /** Discriminator value backing a polymorphic link (when isPolymorphic). */
  polymorphicTypeValue?: string;
}

/**
 * Many-to-many bridge between this entity and a target entity through a
 * junction table. Projected by the server's `_dbSchema` resolver. The UI uses
 * the junction's own multi-join for the rows query and these fields to skip
 * the junction for navigation, drilling straight to the target entity.
 * @interface ManyToManyJoin
 */
export interface ManyToManyJoin {
  /** Junction table GraphQL name (also the relationship name). */
  name: string;
  /** Target entity GraphQL type/table name. */
  targetTable: string;
  /** Junction table GraphQL type/table name. */
  junctionTable: string;
  /** Selection field on the junction type that resolves the target row. */
  junctionTargetField: string;
  /** Key column(s) on this (source) entity. */
  sourceColumnNames: string[];
  /** Junction column(s) referencing this (source) entity. */
  junctionSourceColumnNames: string[];
  /** Junction column(s) referencing the target entity. */
  junctionTargetColumnNames: string[];
  /** Key column(s) on the target entity. */
  targetColumnNames: string[];
  /** True when the junction carries extra (non-key) payload columns to reveal. */
  hasPayload: boolean;
}

/**
 * Table definition from database schema introspection.
 * @interface Table
 */
export interface Table {
  /** Original database table name */
  dbName: string;
  /** GraphQL type name for the table */
  graphQlName: string;
  /** Alias for graphQlName */
  name: string;
  /** Human-readable label for the table */
  label: string;
  /** Column used as the display label for foreign key references */
  labelColumn: string;
  /** Primary key column names */
  primaryKeys: string[];
  /** Whether this table supports mutations */
  isEditable: boolean;
  /** Custom metadata for the table */
  metadata: TableMetadata;
  /** Column definitions */
  columns: Column[];
  /** One-to-many relationship joins */
  multiJoins: Join[];
  /** Many-to-one relationship joins */
  singleJoins: Join[];
  /** Many-to-many bridges through junction tables (optional; absent on older servers). */
  manyToManyJoins?: ManyToManyJoin[];
}

/**
 * Schema context value containing database metadata and loading state.
 * @interface Schema
 */
export interface Schema {
  /** Whether schema data is currently loading */
  loading: boolean;
  /** Error object if schema loading failed, null otherwise */
  error: { message: string} | null;
  /** Array of table definitions */
  data: Table[];
  /** Find a table by its GraphQL name */
  findTable: (tableName: string) => Table | undefined;
}
